#ifndef CONFIG_H
#define CONFIG_H

#define GROSSURA_LINHA 4
#define ALTURA 22
#define LARGURA 40
#define TILE_SIZE 20
#define JANELA_LARGURA (LARGURA * TILE_SIZE)
#define JANELA_ALTURA  (ALTURA * TILE_SIZE)
#define VELOCIDADE_PACMAN 6
#define VELOCIDADE_FANTASMA 5

#endif
